get http://localhost:3009/todos/?status=TO%20DO

###
get http://localhost:3009/todos/?priority=HIGH

###
get http://localhost:3009/todos/?priority=HIGH&status=IN%20PROGRESS

###
get http://localhost:3009/todos/?search_q=Buy

###
get http://localhost:3009/todos/?category=WORK&status=DONE

###
get http://localhost:3009/todos/?category=HOME

###
get http://localhost:3009/todos/?category=LEARNING&priority=HIGH

###
get http://localhost:3009/todos/2/

###

get http://localhost:3009/agenda/?date=2021-2-22

###
post  http://localhost:3009/todos
Content-Type: application/json

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}

###
put http://localhost:3009/todos/1
Content-Type: application/json

{ "status": "DONE" }

###
put http://localhost:3009/todos/2
Content-Type: application/json

{ "priority": "HIGH" }

###
put http://localhost:3009/todos/1
Content-Type: application/json

{
"todo": "Clean the garden"
}

###

put http://localhost:3009/todos/1
Content-Type: application/json

{ "category": "LEARNING" }

###
put http://localhost:3009/todos/1
Content-Type: application/json

{ "dueDate": "2021-01-12" }

###
DELETE http://localhost:3009/todos/1